global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "nodejs_app"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: /metrics
    scheme: http

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
